version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
  app:
    image: modelreg/modelreg:latest
    hostname: modelreg
    volumes:
      - ./storage/html/static:/usr/src/app/static:rw
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - MIGRATE=${MIGRATE}
      - COLLECTSTATIC=${COLLECTSTATIC}
      - UWSGI=${UWSGI}
      - PORT=${PORT}
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
  nginx:
    links:
      - app
    image: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./storage/html:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
