version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=modelreg
      - POSTGRES_PASSWORD=modelreg
      - POSTGRES_DB=modelreg
  app:
    image: modelreg:latest
    hostname: modelreg
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      - DB_TYPE=postgresql
      - DB_USER=modelreg
      - DB_PASSWORD=modelreg
      - DB_NAME=modelreg
      - DB_HOST=db
      - MIGRATE="true"
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=modelreg
      - DEBUG="true"
