"""
Django settings for modelreg project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import random
import string

from django.core.exceptions import ImproperlyConfigured

from modelreg.settings import *


def _make_key(length):
   letters = string.ascii_letters + string.punctuation + string.digits
   return ''.join(random.choice(letters) for _ in range(length))

SECRET_KEY    = os.getenv('SECRET_KEY', _make_key(50))
DEBUG         = os.getenv('DEBUG', 'false').lower() == 'true'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')



_db_configs = {
    'sqlite3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'mysql': {
        'ENGINE':  'django.db.backends.mysql',
        'NAME':     os.getenv('DB_NAME', None),
        'USER':     os.getenv('DB_USER', None),
        'PASSWORD': os.getenv('DB_PASSWORD', None),
        'HOST':     os.getenv('DB_HOST', '127.0.0.1'),
        'PORT':     '3306',
    },
    'postgresql': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     os.getenv('DB_NAME', None),
        'USER':     os.getenv('DB_USER', None),
        'PASSWORD': os.getenv('DB_PASSWORD', None),
        'HOST':     os.getenv('DB_HOST', '127.0.0.1'),
        'PORT':     '5432',
    }
}

DB_TYPE = os.getenv('DB_TYPE', 'sqlite3')

if DB_TYPE not in _db_configs:
    raise ImproperlyConfigured("You have configured an incompatible DB_TYPE")

DATABASES = {
    'default': _db_configs[DB_TYPE]
}
