# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import modelreg.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0002_auto_20170514_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='auth',
            field=models.CharField(default=modelreg.models.make_identifier, max_length=15),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='identifier',
            field=models.CharField(default=modelreg.models.make_identifier, max_length=15),
        ),
        migrations.AddIndex(
            model_name='publicprofile',
            index=models.Index(fields=['identifier', 'auth'], name='modelreg_pu_identif_98b06d_idx'),
        ),
    ]
