# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelreg.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelreg', '0003_auto_20170514_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=modelreg.models.make_identifier, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('model_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('no_damage', 'No Damage'), ('property_damage', 'Property Damage'), ('injury', 'Injury')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_owner', models.BooleanField()),
                ('message', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='modelreg.Case')),
            ],
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='auth',
            field=models.CharField(default='', max_length=10, blank=True),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='identifier',
            field=models.CharField(default=modelreg.models.make_identifier, max_length=10),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['timestamp'], name='modelreg_ca_timesta_41abf9_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['identifier'], name='modelreg_ca_identif_631d28_idx'),
        ),
    ]
