# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0004_auto_20170514_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemessage',
            name='case_type',
        ),
        migrations.AddField(
            model_name='case',
            name='damage_type',
            field=models.CharField(choices=[('no_damage', 'No Damage'), ('property_damage', 'Property Damage'), ('injury', 'Injury')], default='no_damage', max_length=20),
        ),
    ]
