# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import modelreg.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0006_auto_20170912_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprofile',
            name='auth',
            field=models.CharField(blank=True, default=modelreg.models.make_identifier, max_length=15),
        ),
        migrations.AlterField(
            model_name='publicprofile',
            name='identifier',
            field=models.CharField(blank=True, default=modelreg.models.make_identifier, max_length=15),
        ),
    ]
