# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import modelreg.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0007_auto_20170928_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='identifier',
            field=models.CharField(blank=True, default=modelreg.models.make_identifier, max_length=15),
        ),
    ]
