# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0008_auto_20170928_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='admin_informed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='finder_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='owner_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='for_admin',
            field=models.BooleanField(default=False),
        ),
    ]
