# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 19:17
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    CaseMessage = apps.get_model('modelreg', 'CaseMessage')

    from_owner_to_sender = {
        True:  'owner',
        False: 'finder'
    }

    for message in CaseMessage.objects.all():
        message.sender = from_owner_to_sender[message.from_owner]
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0010_casemessage_sender'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
