# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelreg', '0011_migrate_from_owner_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemessage',
            name='from_owner',
        ),
    ]
